version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: park_app
    container_name: park_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      - .env 